version: '3'

networks:
  lb:
    driver: overlay
  internal:
    driver: overlay

services:
  lb:
    image: dockercloud/haproxy
    deploy:
      placement:
        constraints:
          - node.role == manager
    networks:
      - lb
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
      - 443:443

  app:
    networks:
      - lb
      - internal
    deploy:
      placement:
        constraints:
          - node.labels.arch != arm6
          - node.labels.arch != arm7
          - node.labels.arch != arm64
    image: 127.0.1.1:5000/armygeddon_front_x64:0.2.0
    command: node front/app.js
    environment:
      - PORT=3000
      - SERVICE_PORTS=3000
      - BALANCE=source
      - TOKEN_SECRET=my secret
    depends_on:
      - arango
      
  login-service:
    networks:
      - internal
    deploy:
      placement:
        constraints:
          - node.labels.arch == arm6
    image: 127.0.1.1:5000/armygeddon_srv_arm6:0.2.0
    command: node services/login-service.js
    environment:
      - COTE_DISCOVERY_REDIS_HOST=redis
      - TOKEN_SECRET=my secret
    depends_on:
      - arango

  register-service:
    networks:
      - internal
    deploy:
      placement:
        constraints:
          - node.labels.arch == arm6
    image: 127.0.1.1:5000/armygeddon_srv_arm6:0.2.0
    command: node services/register-service.js
    environment:
      - COTE_DISCOVERY_REDIS_HOST=redis
      - TOKEN_SECRET=my secret
    depends_on:
      - arango

  army-service:
    networks:
      - internal
    deploy:
      placement:
        constraints:
          - node.labels.arch == arm6
    image: 127.0.1.1:5000/armygeddon_srv_arm6:0.2.0
    command: node services/army-service.js
    depends_on:
      - arango

  battle-service:
    networks:
      - internal
    deploy:
      placement:
        constraints:
          - node.labels.arch == arm7
    image: 127.0.1.1:5000/armygeddon_srv_arm7:0.2.0
    command: node services/battle-service.js
    depends_on:
      - arango

  battle-tracker-service:
    networks:
      - internal
    deploy:
      placement:
        constraints:
          - node.labels.arch == arm6
    image: 127.0.1.1:5000/armygeddon_srv_arm6:0.2.0
    command: node services/battle-tracker-service.js
    depends_on:
      - arango
    
  player-service:
    networks:
      - internal
    deploy:
      placement:
        constraints:
          - node.labels.arch == arm6
    image: 127.0.1.1:5000/armygeddon_srv_arm6:0.2.0
    command: node services/player-service.js
    environment:
      - ARANGO_INIT=1
    depends_on:
      - arango

  map-service:
    networks:
      - internal
    deploy:
      placement:
        constraints:
          - node.labels.arch == arm6
    image: 127.0.1.1:5000/armygeddon_srv_arm6:0.2.0
    command: node services/map-service.js
    depends_on:
      - arango

  battle-template-service:
    networks:
      - internal
    deploy:
      placement:
        constraints:
          - node.labels.arch == arm6
    image: 127.0.1.1:5000/armygeddon_srv_arm6:0.2.0
    command: node services/battle-template-service.js
    depends_on:
      - arango

  redis:
    image: redis:5.0.7-alpine
    networks:
      - internal
    deploy:
      placement:
        constraints:
          - node.labels.arch != arm6
    ports:
      - 6379:6379
    
  arango:
    networks:
      - internal
    deploy:
      placement:
        constraints:
          - node.labels.arch == x64
          - node.labels.os != win10
    image: arangodb:3.3
    ports:
      - 8529:8529
    environment:
      - ARANGO_NO_AUTH=1
    volumes:
      - /arangodb:/var/lib/arangodb3