FROM mhart/alpine-node:12
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci --prod

# Only copy over the node pieces we need from the above image
FROM arm32v6/node:12-alpine
WORKDIR /app
COPY --from=0 /app .
COPY ./src .