version: '3'

networks:
  lb:
    driver: overlay
  internal:
    driver: overlay

services:
  app:
    networks:
      - lb
      - internal
    deploy:
      placement:
        constraints:
          - node.labels.arch != arm6
          - node.labels.arch != arm7
          - node.labels.arch != arm64
    image: 127.0.1.1:5000/armygeddon_front_x64:0.2.0
    command: node front/app.js
    environment:
      - PORT=80
      - TOKEN_SECRET=my secret
      - COTE_DISCOVERY_REDIS_HOST=redis
    depends_on:
      - arango
      - redis
    ports: 
      - 80:80

  army-service:
    networks:
      - internal
    deploy:
      placement:
        constraints:
          - node.labels.arch == arm6
    image: 127.0.1.1:5000/armygeddon_srv_arm6:0.2.0
    command: node services/army-service.js
    environment:
      - COTE_DISCOVERY_REDIS_HOST=redis
      - ARANGO_URL=http://arango:8529
      - ARANGO_DB=armygeddon
    depends_on:
      - arango
      - redis

  battle-service:
    networks:
      - internal
    deploy:
      placement:
        constraints:
          - node.labels.arch == arm6
    image: 127.0.1.1:5000/armygeddon_srv_arm6:0.2.0
    command: node services/battle-service.js
    environment:
      - COTE_DISCOVERY_REDIS_HOST=redis
      - ARANGO_URL=http://arango:8529
      - ARANGO_DB=armygeddon
    depends_on:
      - arango
      - redis

  battle-tracker-service:
    networks:
      - internal
    deploy:
      placement:
        constraints:
          - node.labels.arch == arm6
    image: 127.0.1.1:5000/armygeddon_srv_arm6:0.2.0
    command: node services/battle-tracker-service.js
    environment:
      - COTE_DISCOVERY_REDIS_HOST=redis
      - ARANGO_URL=http://arango:8529
      - ARANGO_DB=armygeddon
    depends_on:
      - arango
      - redis
    
  player-service:
    networks:
      - internal
    deploy:
      placement:
        constraints:
          - node.labels.arch == arm6
    image: 127.0.1.1:5000/armygeddon_srv_arm6:0.2.0
    command: node services/player-service.js
    environment:
      - COTE_DISCOVERY_REDIS_HOST=redis
      - ARANGO_URL=http://arango:8529
      - ARANGO_DB=armygeddon
      - ARANGO_INIT=1
    depends_on:
      - arango
      - redis

  map-service:
    networks:
      - internal
    deploy:
      placement:
        constraints:
          - node.labels.arch == arm6
    image: 127.0.1.1:5000/armygeddon_srv_arm6:0.2.0
    command: node services/map-service.js
    environment:
      - COTE_DISCOVERY_REDIS_HOST=redis
      - ARANGO_URL=http://arango:8529
      - ARANGO_DB=armygeddon
    depends_on:
      - arango
      - redis

  battle-template-service:
    networks:
      - internal
    deploy:
      placement:
        constraints:
          - node.labels.arch == arm6
    image: 127.0.1.1:5000/armygeddon_srv_arm6:0.2.0
    command: node services/battle-template-service.js
    environment:
      - COTE_DISCOVERY_REDIS_HOST=redis
      - ARANGO_URL=http://arango:8529
      - ARANGO_DB=armygeddon
    depends_on:
      - arango
      - redis

    ruleset-service:
      networks:
        - internal
      deploy:
        placement:
          constraints:
            - node.labels.arch == arm6
      image: 127.0.1.1:5000/armygeddon_srv_arm6:0.2.0
      command: node services/ruleset-service.js
      environment:
        - COTE_DISCOVERY_REDIS_HOST=redis
        - ARANGO_URL=http://arango:8529
        - ARANGO_DB=armygeddon
      depends_on:
        - arango
        - redis

  pattern-service:
    networks:
      - internal
    deploy:
      placement:
        constraints:
          - node.labels.arch == x64
    image: 127.0.1.1:5000/armygeddon_srvai_x64:0.2.0
    command: node services/pattern-service.js
    environment:
      - COTE_DISCOVERY_REDIS_HOST=redis
      - ARANGO_URL=http://arango:8529
      - ARANGO_DB=armygeddon
    depends_on:
      - arango
      - redis

  redis:
    image: redis:5.0.7-alpine
    networks:
      - internal
    deploy:
      placement:
        constraints:
          - node.labels.arch != arm6
    ports:
      - 6379:6379
    
  arango:
    networks:
      - internal
    deploy:
      placement:
        constraints:
          - node.labels.arch == x64
          - node.labels.os != win10
    image: arangodb:3.3
    ports:
      - 8529:8529
    environment:
      - ARANGO_NO_AUTH=1
    volumes:
      - /arangodb:/var/lib/arangodb3
